// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwodtrbdaqikszkmlfwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3b2R0cmJkYXFpa3N6a21sZndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NDAxNTMsImV4cCI6MjA1MTQxNjE1M30.ulTHLPHMzqg5DyO51ncOMfhRNzZ9O1wD8ZddviB-lhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);